// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDatasets() {
  return window['go']['client']['App']['CheckDatasets']();
}

export function ChooseFile() {
  return window['go']['client']['App']['ChooseFile']();
}

export function Debug(arg1) {
  return window['go']['client']['App']['Debug'](arg1);
}

export function Error(arg1) {
  return window['go']['client']['App']['Error'](arg1);
}

export function Fatal(arg1) {
  return window['go']['client']['App']['Fatal'](arg1);
}

export function FetchProxies() {
  return window['go']['client']['App']['FetchProxies']();
}

export function GetProfile() {
  return window['go']['client']['App']['GetProfile']();
}

export function Info(arg1) {
  return window['go']['client']['App']['Info'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['client']['App']['SaveConfig'](arg1);
}

export function StopListening() {
  return window['go']['client']['App']['StopListening']();
}

export function UseFetchedDatasets() {
  return window['go']['client']['App']['UseFetchedDatasets']();
}

export function Warn(arg1) {
  return window['go']['client']['App']['Warn'](arg1);
}
