// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {config} from '../models';

export function CheckDatasets():Promise<client.Response>;

export function ChooseFile():Promise<config.Config>;

export function Debug(arg1:Array<any>):Promise<void>;

export function Error(arg1:Array<any>):Promise<void>;

export function Fatal(arg1:Array<any>):Promise<void>;

export function FetchProxies():Promise<client.Response>;

export function GetProfile():Promise<config.Config>;

export function Info(arg1:Array<any>):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function StopListening():Promise<client.Response>;

export function UseFetchedDatasets():Promise<client.Response>;

export function Warn(arg1:Array<any>):Promise<void>;
