package request

import (
	"bytes"
	"crypto/tls"
	"doki-byte/FreeProxy/backend/config"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"strconv"
	"time"
)

type QuakeData struct {
	Query string `json:"query"`
	Start int    `json:"start"`
	Size  int    `json:"size"`
}

type QuakeAutoGenerated struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    []struct {
		Hostname string `json:"hostname"`
		Org      string `json:"org"`
		Port     int    `json:"port"`
		Service  struct {
			Response     string `json:"response"`
			ResponseHash string `json:"response_hash"`
			Name         string `json:"name"`
			Version      string `json:"version"`
			Socks5       struct {
				AuthAcceptedMethod string `json:"auth_accepted_method"`
				Version            int    `json:"version"`
			} `json:"socks5"`
		} `json:"service"`
		Ip        string `json:"ip"`
		OsVersion string `json:"os_version"`
		OsName    string `json:"os_name"`
		Location  struct {
			Owner       string    `json:"owner"`
			ProvinceCn  string    `json:"province_cn"`
			ProvinceEn  string    `json:"province_en"`
			Isp         string    `json:"isp"`
			CountryEn   string    `json:"country_en"`
			DistrictCn  string    `json:"district_cn"`
			Gps         []float64 `json:"gps"`
			StreetCn    string    `json:"street_cn"`
			CityEn      string    `json:"city_en"`
			DistrictEn  string    `json:"district_en"`
			CountryCn   string    `json:"country_cn"`
			StreetEn    string    `json:"street_en"`
			CityCn      string    `json:"city_cn"`
			CountryCode string    `json:"country_code"`
			Asname      string    `json:"asname"`
			SceneCn     string    `json:"scene_cn"`
			SceneEn     string    `json:"scene_en"`
			Radius      int       `json:"radius"`
		} `json:"location"`
		IsIpv6    bool      `json:"is_ipv6"`
		Transport string    `json:"transport"`
		Time      time.Time `json:"time"`
		Asn       int       `json:"asn"`
	} `json:"data"`
	Meta struct {
		Pagination struct {
			Count     int `json:"count"`
			PageIndex int `json:"page_index"`
			PageSize  int `json:"page_size"`
			Total     int `json:"total"`
		} `json:"pagination"`
	} `json:"meta"`
}

func quake_api(keyword string, start int, size int) QuakeData {
	reqData := QuakeData{}
	reqData.Query = keyword
	reqData.Start = start
	reqData.Size = size

	return reqData
}

func quakehttp(postdata QuakeData, key string, timeout string) *QuakeAutoGenerated {
	var itime, err = strconv.Atoi(timeout)
	if err != nil {
		log.Println("quake超时参数错误: ", err)
	}
	transport := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
	client := &http.Client{
		Timeout:   time.Duration(itime) * time.Second,
		Transport: transport,
	}
	url := "https://quake.360.net/api/v3/search/quake_service"
	payload, _ := json.Marshal(postdata)
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(payload))
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("content-type", "application/json")
	req.Header.Set("User-Agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36")
	req.Header.Set("X-QuakeToken", key)
	resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	result, _ := io.ReadAll(resp.Body)
	res := &QuakeAutoGenerated{}
	json.Unmarshal(result, &res)
	return res
}

func Quakeall(keyword string) (urls []string) {
	quake := config.GetConfig()
	postdata := quake_api(keyword, 0, 50)
	res := quakehttp(postdata, quake.QuakeKey, quake.Timeout)
	pagelength := res.Meta.Pagination.Total/50 + 1
	for _, value := range res.Data {
		urls = append(urls, value.Ip+":"+strconv.Itoa(value.Port))
	}
	Maxpage, _ := strconv.Atoi(quake.Maxpage)
	if pagelength > 1 {
		for i := 1; i <= pagelength && i <= Maxpage*2; i++ {
			fmt.Println("正在请求第" + strconv.Itoa(i) + "页数据")
			postdata = quake_api(keyword, i*50, 50)
			res = quakehttp(postdata, quake.QuakeKey, quake.Timeout)
			if len(res.Data) > 0 {
				for _, value := range res.Data {
					urls = append(urls, value.Ip+":"+strconv.Itoa(value.Port))
				}
			} else {
				break
			}
		}
	}

	return urls
}

type QuakeConfig struct{}

func (fp *QuakeConfig) Name() string {
	return "Quake"
}

func (fp *QuakeConfig) Fetch() ([]string, error) {
	quake := config.GetConfig()

	var quakekeys string

	if quake.QuakeKey != "" {
		switch quake.Country {
		case "0":
			quakekeys = fmt.Sprintf("service:\"socks5\" and response:\"Accepted Auth Method: 0x0\"")
		case "1":
			quakekeys = fmt.Sprintf("service:\"socks5\" and response:\"Accepted Auth Method: 0x0\" and country: \"China\"")
		case "2":
			quakekeys = fmt.Sprintf("service:\"socks5\" and response:\"Accepted Auth Method: 0x0\" and not country: \"China\"")
		}
		urls := Quakeall(quakekeys)
		return urls, nil
	} else {
		return nil, nil
	}
}
